### ISSUE TITLE
Cleaning the markup from the text

### ISSUE THREAD

**Issue by szkaus** [fastily/jwiki#24]
Hi,

Thanks for your project, really good one. I tried your jwiki starter. While I get the text from the wikipedia article, it would be good to have something that removes the wikipedia markup and outputs clean text. 

**Example output:**
_Some native animals are also adept at surviving bushfires.<ref>Effects of fire on plants and animals {{cite web......_

**Desired output:**
_Some native animals are also adept at surviving bushfires_

**Comment by fastily** [comment]
Hi @szkaus:

After researching this, I do not believe this is possible with the vanilla MediaWiki API.

Possible solutions:
* if you download the page as HTML, you can use [jsoup](https://jsoup.org) to [strip tags](https://stackoverflow.com/questions/12943734/jsoup-strip-all-formatting-and-link-tags-keep-text-only)
* [mwparserfromhell](https://github.com/earwig/mwparserfromhell) might have this capability, but requires python.

Closing this now, because the main goal of jwiki is to provide a simple wrapper for the MediaWiki API, and implementing a parser to strip tags is out of scope imo
