### ISSUE TITLE
`Wiki#prefixIndex` is improperly documented

### ISSUE THREAD

**Issue by SizableShrimp** [fastily/jwiki#30]
The documentation for `Wiki#prefixIndex` states:
```
Does the same thing as Special:PrefixIndex.
```

However, this is incorrect. Looking at the MediaWiki documentation, it states:
```
Perform a prefix search for page titles.

Despite the similarity in names, this module is not intended to be equivalent to Special:PrefixIndex; for that, see action=query&list=allpages with the apprefix parameter. The purpose of this module is similar to action=opensearch: to take user input and provide the best-matching titles. Depending on the search engine backend, this might include typo correction, redirect avoidance, or other heuristics. 
```

This means that `Wiki#prefixIndex` should have its documentation updated to state this fact. The actual method that should note it does the same thing as Special:PrefixIndex should be `Wiki#allPages`, as noted in the MediaWiki documentation.

I also have a fork I am maintaining with updates to jwiki at [SizableShrimp/jwiki](https://github.com/SizableShrimp/jwiki), e.g. caching login values and retrying requests after logging in if a `badtoken` error is received along with other general updates and improvements. I haven't made a PR for these changes because they cause breaking API changes and also my fork is slightly modified to be compatible with [Jitpack](https://jitpack.io) so that I don't have to host my own maven repo. Let me know if you would like to receive a PR with these changes in the near future.

**Comment by fastily** [comment]
Hi @SizableShrimp ,

Thanks for the bug report, I'll modify the documentation reflect this.

Sure, please feel free to PR improvements.  I created jwiki in 2013 to learn more about Java, and if I'm going to be perfectly honest with you, a number of the architectural decisions I made back then haven't aged particularly well.

For any PRs, could you please:
* keep breaking changes to an absolute minimum (for the record, I'd love to do an overhaul with a 2.0 release, but I'm hesitant because it'll be a turn-off to downstream users)
* use jwiki's codestyle ([here is the eclipse formatter profile](https://github.com/fastily/jwiki/blob/gh-pages/resources/jwiki%20code%20style.xml))
